apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: [""]
    resources: ["services","endpoints","pods", "nodes"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image:  extdnscr.azurecr.io/extdnsnofixapp:v92  # 70, 80 worked. Latest 90,91 image worked for retry.
          env:
            #- name: AZURE_CLIENT_MAX_RETRY_COUNT
            #  value: "2"
            - name: AZURE_SDK_MAX_RETRIES
              value: "-1"
            - name: AZURE_SDK_GO_LOGGING
              value: "all"
            - name: AZURE_SDK_GO_LOGGING_LEVEL
              value: "debug"
          args:
            - --source=service
            - --source=ingress
          #  - --domain-filter=example1.com # (optional) limit to only example.com domains; change to match the zone created above.
            - --provider=azure-private-dns
            - --azure-resource-group=ExtDNSNoFix-RG # (optional) use the DNS zones from the tutorial's resource group
            - --azure-subscription-id=58768663-9606-45cf-a196-136d98585866
            - --log-level=debug
            - --interval=1s
          #  - --azure-retry-max=4
          volumeMounts:
            - name: azure-config-file
              mountPath: /etc/kubernetes
              readOnly: true

      volumes:
        - name: azure-config-file
          secret:
            secretName: azure-config-file