---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: mcr.microsoft.com/azurelinux/base/nginx:1.25
          name: nginx
          ports:
          - containerPort: 80